version: '3.7'

services:
  mysql:
    image: mysql:5.7
#    platform: linux/x86_64
    restart: unless-stopped
    container_name: docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_db
    ports:
      - "3306:3306"
