version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    container_name: docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_shortener_service_spring_boot
    ports:
      - "3306:3306"
